/**
 * The runner, the environment and the outbound-HTTP double.
 *
 * No framework and no new dependency: node:assert and the type stripping the
 * repository already runs its V1 suite with. The one thing added over that suite
 * is that every test declares which requirements of SPEC-BRIDGE-V2 it exercises,
 * so the requirement-to-test map in the report is produced by the suite rather
 * than written alongside it and left to drift.
 *
 * CREDENTIALS. Nothing in this file or anywhere under test/ is a real key. The
 * wallet seed is the Hardhat/Anvil documentation mnemonic, which is public, whose
 * accounts are known to everybody and hold nothing on any real network. Every
 * other secret-shaped value is generated by crypto.getRandomValues at the moment
 * the process starts and exists only in this process's memory.
 */

import assert from 'node:assert/strict';

/**
 * The public Hardhat/Anvil test mnemonic. Not a secret: it is in the Hardhat
 * documentation and its addresses are known to everyone. The real derivation
 * root lives only in the Vercel environment and never in a file.
 */
export const TEST_MNEMONIC = 'test test test test test test test test test test test junk';

const randomHex = (bytes) => {
  const buffer = new Uint8Array(bytes);
  crypto.getRandomValues(buffer);
  return [...buffer].map((byte) => byte.toString(16).padStart(2, '0')).join('');
};

/** Two funder keys, generated here, used only by this process. */
export const TEST_FUNDER_KEYS = [`0x${randomHex(32)}`, `0x${randomHex(32)}`];
export const TEST_ROLE_KEY = `0x${randomHex(32)}`;
export const TEST_CRON_SECRET = randomHex(32);
export const TEST_TELEGRAM_SECRET = randomHex(32);

/**
 * Every name in REQUIRED_ENV, filled with a generated value.
 *
 * Set before any production module is imported, because config.ts runs its
 * invariants at import time and several modules read the environment at the
 * moment of use.
 */
export function installEnv() {
  Object.assign(process.env, {
    SUPABASE_URL: 'https://project.supabase.invalid',
    SUPABASE_SERVICE_KEY: `sb_secret_${randomHex(16)}`,
    BRIDGE_V2_WALLET_SEED: TEST_MNEMONIC,
    BRIDGE_V2_CODE_HMAC_KEY: randomHex(32),
    BRIDGE_V2_PHONE_HMAC_KEY: randomHex(32),
    BRIDGE_V2_SESSION_HMAC_KEY: randomHex(32),
    BRIDGE_V2_SIGNAL_HMAC_KEY: randomHex(32),
    BRIDGE_V2_FUNDER_KEYS: TEST_FUNDER_KEYS.join(','),
    BRIDGE_V2_ROLE_KEY: TEST_ROLE_KEY,
    RESEND_API_KEY: `re_${randomHex(16)}`,
    BRIDGE_V2_MAIL_FROM: 'Events <no-reply@example.invalid>',
    TELEGRAM_BOT_TOKEN: `${randomHex(4)}:${randomHex(16)}`,
    TELEGRAM_WEBHOOK_SECRET: TEST_TELEGRAM_SECRET,
    TELEGRAM_BOT_USERNAME: 'example_events_bot',
    CRON_SECRET: TEST_CRON_SECRET,
  });
}

// ---------------------------------------------------------------------------
// outbound HTTP
// ---------------------------------------------------------------------------

/**
 * Replaces globalThis.fetch, so mail.ts, telegram.ts, alert.ts and the DNS-over-
 * HTTPS lookup in identity.ts run their real code against a recorded transport.
 * Doubling the transport rather than the modules is what keeps the timeout, the
 * abort wiring and the request bodies under test.
 */
export const http = {
  requests: [],
  /** url pattern -> (url, init) => Response | Error */
  routes: [],
  reset() {
    http.requests.length = 0;
    http.routes.length = 0;
  },
  on(pattern, handler) {
    http.routes.push([pattern, handler]);
  },
};

/**
 * The transport before it was replaced.
 *
 * Exported so the one suite that is allowed out — the read-only checks against
 * Arbitrum One — can register a route that goes to the real network. Nothing
 * else may use it: a test that reaches a provider passes or fails on somebody
 * else's uptime.
 */
export const realFetch = globalThis.fetch;

export function installFetchDouble() {
  globalThis.fetch = async (input, init = {}) => {
    const url = typeof input === 'string' ? input : String(input?.url ?? input);
    http.requests.push({ url, init, body: init.body });
    for (const [pattern, handler] of http.routes) {
      if (url.includes(pattern)) {
        const result = await handler(url, init);
        if (result instanceof Error) throw result;
        return result;
      }
    }
    // Unprogrammed: refused rather than allowed out. A test that reaches the
    // network is a test that would pass or fail on somebody else's uptime.
    throw new Error(`[test] no double for outbound fetch to ${url}`);
  };
}

export function restoreFetch() {
  globalThis.fetch = realFetch;
}

export const jsonResponse = (body, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });

// ---------------------------------------------------------------------------
// the runner
// ---------------------------------------------------------------------------

/** One entry per test: which requirements it covers, and how it ended. */
export const results = [];

let currentSuite = 'unknown';
export function suite(name) {
  currentSuite = name;
}

/**
 * Declares one test.
 *
 * `requirements` is the list of SPEC-BRIDGE-V2 identifiers the test exercises.
 * The report's requirement map is built from these, so a test that covers
 * nothing declares nothing and a requirement with no test is visible as a gap
 * rather than as an omission somebody has to notice.
 */
export async function test(requirements, name, body) {
  const entry = { suite: currentSuite, requirements, name, ok: false, error: null };
  results.push(entry);
  try {
    await body();
    entry.ok = true;
  } catch (error) {
    entry.error = error instanceof Error ? (error.stack ?? error.message) : String(error);
  }
}

export { assert };

/** Builds a Request the way the platform hands one to a route. */
export function request(url, { method = 'POST', body, headers = {}, cookie } = {}) {
  const finalHeaders = {
    'content-type': 'application/json',
    'x-forwarded-for': '198.51.100.7',
    'user-agent': 'test-agent',
    ...headers,
  };
  if (cookie !== undefined) finalHeaders.cookie = cookie;
  return new Request(url, {
    method,
    headers: finalHeaders,
    body: body === undefined ? undefined : JSON.stringify(body),
  });
}

/** A logger double, so a test can read what a route recorded without a table. */
export function recordingLogger() {
  const events = [];
  return {
    correlationId: 'test-correlation',
    events,
    event: async (kind, detail = {}) => {
      events.push({ kind, detail });
    },
    failure: async (kind, error, detail = {}) => {
      events.push({ kind, detail, error });
    },
  };
}

/** A run deadline double with a fixed answer, so a test controls G4 directly. */
export function deadline(hasTime = true, remaining = 280_000) {
  return { hasTimeFor: () => hasTime, remainingMs: () => remaining };
}
