/**
 * The Postgres the migrations are actually run against.
 *
 * WHY THIS EXISTS. 0004, 0005 and 0006 had never been executed anywhere. They
 * were checked by reading them and by a parser (suites/sql.test.mjs, which says
 * so in its own header), and a parser cannot tell you that a partial unique
 * index fires, that an ON CONFLICT ... WHERE returns no row, that a plpgsql
 * EXCEPTION block keeps the work done before it, or that a REVOKE reached the
 * function it named. Those are the properties the requirements are made of.
 *
 * THE ENGINE. embedded-postgres, a devDependency, which unpacks the official
 * PostgreSQL 17.10 binaries and runs a real cluster on a loopback port out of a
 * temporary directory. It is not an emulator and not an in-process
 * reimplementation: it is postgres.exe. That matters for two of the questions
 * asked of it -- concurrency and privileges -- because both are properties of
 * the server and neither survives being modelled.
 *
 * WHAT IT IS NOT. It is not Supabase. Supabase supplies the roles, the
 * `extensions` schema, the default privileges on `public` and PostgREST; this
 * file recreates the first three because the migrations depend on them, and
 * nothing here can recreate the fourth. Every difference we found is listed in
 * the report under "divergencias do motor".
 *
 * CREDENTIALS. The cluster's superuser password is generated by
 * crypto.getRandomValues at boot, lives in this process's memory, is never
 * written to a project file and dies with the process. Rule 0.1.
 */

import EmbeddedPostgres from 'embedded-postgres';
import pg from 'pg';
import net from 'node:net';
import os from 'node:os';
import path from 'node:path';
import fs from 'node:fs/promises';
import { readFileSync } from 'node:fs';

const MIGRATIONS = new URL('../../supabase/migrations/', import.meta.url);

export const readMigration = (file) => readFileSync(new URL(file, MIGRATIONS), 'utf8');

const randomHex = (bytes) => {
  const buffer = new Uint8Array(bytes);
  crypto.getRandomValues(buffer);
  return [...buffer].map((byte) => byte.toString(16).padStart(2, '0')).join('');
};

/** A port the operating system has just told us is free. */
const freePort = () =>
  new Promise((resolve, reject) => {
    const server = net.createServer();
    server.on('error', reject);
    server.listen(0, '127.0.0.1', () => {
      const { port } = server.address();
      server.close(() => resolve(port));
    });
  });

/**
 * The roles a Supabase project already has when a migration runs against it.
 * service_role carries BYPASSRLS; the other three do not.
 */
const ROLES = `
  CREATE ROLE anon          NOLOGIN NOINHERIT;
  CREATE ROLE authenticated NOLOGIN NOINHERIT;
  CREATE ROLE service_role  NOLOGIN NOINHERIT BYPASSRLS;
  CREATE ROLE authenticator LOGIN   NOINHERIT;
  GRANT anon, authenticated, service_role TO authenticator;
`;

/**
 * The schema shape, and the half that is easy to forget: Supabase sets ALTER
 * DEFAULT PRIVILEGES in `public` granting ALL on tables, functions and sequences
 * to anon, authenticated and service_role, so a table created by a migration is
 * readable and writable by the two browser roles from the moment it exists, with
 * nothing but RLS in front of it. Recreating that here is what makes the 0006
 * REVOKE sweep a test rather than a formality.
 */
const SCHEMA_SHAPE = `
  CREATE SCHEMA IF NOT EXISTS extensions;
  GRANT USAGE ON SCHEMA extensions TO anon, authenticated, service_role;
  GRANT USAGE ON SCHEMA public     TO anon, authenticated, service_role;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES    TO anon, authenticated, service_role;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon, authenticated, service_role;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
`;

/**
 * citext where the target has it.
 *
 * Supabase installs extensions into `extensions`, not into `public`, and
 * `CREATE EXTENSION IF NOT EXISTS citext` in 0004 is therefore a no-op against a
 * real project. That is precisely the case the three `SET search_path = public,
 * extensions` lines exist for, so it is the one the migrations are applied under
 * here. The other case -- citext absent, 0004 creating it in public -- is
 * applied to its own database in the suite, because "works in both" is what
 * those lines claim.
 */
const CITEXT_IN_EXTENSIONS = `CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA extensions;`;

let cluster = null;
let clusterDir = null;
export const serverLog = [];

/**
 * Boots the cluster once per process. Returns the engine's own version string,
 * which the report quotes rather than paraphrases.
 */
export async function bootEngine() {
  if (cluster) return cluster;

  clusterDir = path.join(os.tmpdir(), `bridge-v2-pg-${randomHex(8)}`);
  const port = await freePort();
  const password = randomHex(24);

  const engine = new EmbeddedPostgres({
    databaseDir: clusterDir,
    user: 'postgres',
    password,
    port,
    persistent: false,
    // The server talks to stderr about every connection; keep it out of the
    // suite output but keep it, because a divergence usually announces itself
    // there first.
    onLog: (message) => serverLog.push(String(message).trim()),
    onError: (message) => serverLog.push(String(message).trim()),
  });

  await engine.initialise();
  await engine.start();

  cluster = { engine, port, password, version: null, settings: [], databases: [] };

  const probe = new pg.Pool({
    host: '127.0.0.1', port, user: 'postgres', password, database: 'postgres', max: 1,
  });
  cluster.version = (await probe.query('SELECT version()')).rows[0].version;
  cluster.settings = (
    await probe.query(
      `SELECT name, setting FROM pg_settings
        WHERE name IN ('server_version','TimeZone','lc_collate',
                       'standard_conforming_strings','default_transaction_isolation')
        ORDER BY name`,
    )
  ).rows;
  await probe.end();

  return cluster;
}

export async function stopEngine() {
  if (!cluster) return;
  for (const database of cluster.databases) await database.pool.end().catch(() => {});
  await cluster.engine.stop().catch(() => {});
  await fs.rm(clusterDir, { recursive: true, force: true }).catch(() => {});
  cluster = null;
}

/**
 * A fresh database, shaped like the target project.
 *
 * `withCitext` false leaves the extension out, so 0004 has to create it itself.
 */
export async function createDatabase(name, { withCitext = true } = {}) {
  const { port, password } = await bootEngine();

  const admin = new pg.Client({
    host: '127.0.0.1', port, user: 'postgres', password, database: 'postgres',
  });
  await admin.connect();
  // The roles are cluster-wide: created once, already there for every database
  // after the first.
  try {
    await admin.query(ROLES);
  } catch (error) {
    if (error.code !== '42710') throw error; // duplicate_object
  }
  await admin.query(`DROP DATABASE IF EXISTS ${name}`);
  await admin.query(`CREATE DATABASE ${name}`);
  await admin.end();

  const pool = new pg.Pool({
    host: '127.0.0.1',
    port,
    user: 'postgres',
    password,
    database: name,
    max: 16,
    // A concurrency test that deadlocks must fail rather than stall the suite.
    statement_timeout: 20_000,
  });

  const bootstrap = new pg.Client({
    host: '127.0.0.1', port, user: 'postgres', password, database: name,
  });
  await bootstrap.connect();
  await bootstrap.query(SCHEMA_SHAPE);
  if (withCitext) await bootstrap.query(CITEXT_IN_EXTENSIONS);
  await bootstrap.end();

  const database = { name, pool, port, password };
  cluster.databases.push(database);
  return database;
}

/**
 * file:line for a Postgres error, from the offset the server reports.
 *
 * An error with no position -- most runtime errors -- is reported against the
 * statement the server echoed back instead, so a finding always carries
 * something a reader can look up rather than a message on its own.
 */
export function locate(file, text, error) {
  const offset = Number(error.position ?? 0);
  if (offset > 0) return `${file}:${text.slice(0, offset - 1).split('\n').length}`;
  const internal = error.internalQuery ?? error.where ?? null;
  if (internal) {
    const first = String(internal).trim().split('\n')[0];
    const index = text.indexOf(first);
    if (index >= 0) return `${file}:${text.slice(0, index).split('\n').length}`;
  }
  return `${file}:?`;
}

/**
 * Applies one migration file the way the target applies it: the whole file, one
 * connection, one simple-query message, so the `SET search_path` at the top is
 * in force for every statement below it -- which is the only reason the citext
 * parameters in 0005 and 0006 resolve at all.
 */
export async function applyMigration(database, file) {
  const text = readMigration(file);
  const client = await database.pool.connect();
  const started = Date.now();
  try {
    await client.query(text);
    return { ok: true, file, ms: Date.now() - started };
  } catch (error) {
    return {
      ok: false,
      file,
      ms: Date.now() - started,
      at: locate(file, text, error),
      code: error.code,
      message: error.message,
      detail: error.detail ?? null,
      hint: error.hint ?? null,
      text: `${error.code} ${error.message}${error.detail ? ` | ${error.detail}` : ''}`,
    };
  } finally {
    client.release();
  }
}

/** Every bridge_v2 table 0004 creates, read from the catalog rather than the file. */
export async function bridgeTables(database) {
  const { rows } = await database.pool.query(
    `SELECT tablename FROM pg_tables
      WHERE schemaname = 'public' AND tablename LIKE 'bridge\\_v2\\_%'
      ORDER BY tablename`,
  );
  return rows.map((row) => row.tablename);
}

/** Every bridge_v2 function 0005 creates, with its identity, from the catalog. */
export async function bridgeFunctions(database) {
  const { rows } = await database.pool.query(
    `SELECT p.proname                                  AS name,
            pg_get_function_identity_arguments(p.oid)  AS args,
            p.oid::regprocedure::text                  AS signature,
            p.oid::bigint                              AS oid,
            p.prosecdef                                AS security_definer,
            p.proconfig                                AS config,
            p.proacl::text                             AS acl
       FROM pg_proc p
       JOIN pg_namespace n ON n.oid = p.pronamespace
      WHERE n.nspname = 'public' AND p.proname LIKE 'bridge\\_v2\\_%'
      ORDER BY p.proname, p.oid`,
  );
  return rows;
}

/** Empties every bridge table so one test cannot read another's rows. */
export async function reset(database) {
  const tables = await bridgeTables(database);
  if (tables.length === 0) return;
  await database.pool.query(
    `TRUNCATE ${tables.map((table) => `public.${table}`).join(', ')} RESTART IDENTITY CASCADE`,
  );
  await database.pool.query(`SELECT setval('bridge_v2_wallet_index_seq', 0, false)`);
  await database.pool.query(`SELECT setval('bridge_v2_run_seq', 0, false)`);
}

/** One query on its own connection. */
export const sql = (database, text, values = []) => database.pool.query(text, values);

/** One query, one row, one column, for the many assertions that want a value. */
export async function value(database, text, values = []) {
  const result = await database.pool.query(text, values);
  if (result.rows.length === 0) return undefined;
  return Object.values(result.rows[0])[0];
}

/**
 * n calls, each on its own connection, each in its own transaction, all released
 * at the same moment.
 *
 * The barrier is the point. Opening n transactions and running them one after
 * the other tests nothing; every one of them has to be inside its transaction,
 * holding whatever locks it takes, before any of them is allowed to proceed.
 * The gate opens once all n have connected and issued BEGIN.
 */
export async function concurrently(database, count, body) {
  let open;
  const gate = new Promise((resolve) => { open = resolve; });
  let arrived = 0;
  let ready;
  const allArrived = new Promise((resolve) => { ready = resolve; });

  const runs = Array.from({ length: count }, async (_unused, index) => {
    const client = await database.pool.connect();
    try {
      await client.query('BEGIN');
      if (++arrived === count) ready();
      await gate;
      const produced = await body(client, index);
      await client.query('COMMIT');
      return { ok: true, value: produced };
    } catch (error) {
      await client.query('ROLLBACK').catch(() => {});
      return { ok: false, error, code: error.code, message: error.message };
    } finally {
      client.release();
    }
  });

  await allArrived;
  open();
  return Promise.all(runs);
}

/** Runs `body` with the session role set to `role`, and puts it back afterwards. */
export async function asRole(database, role, body) {
  const client = await database.pool.connect();
  try {
    await client.query(`SET ROLE ${role}`);
    return await body(client);
  } finally {
    await client.query('RESET ROLE').catch(() => {});
    client.release();
  }
}

/** What one statement did, as a value, so a test can assert on a refusal. */
export async function attempt(client, text, values = []) {
  try {
    const result = await client.query(text, values);
    return { ok: true, rows: result.rows, rowCount: result.rowCount };
  } catch (error) {
    return { ok: false, code: error.code, message: error.message };
  }
}

export const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
