/**
 * Deep-link codes. Step 1 of the 05/09/2026 decision.
 *
 * The participant fills the campaign form, and the button opens the bot with a
 * start parameter. That parameter is this code: random, single use, generated by
 * the bridge, and bound to one campaign and one participant.
 *
 * Binding is what stops the obvious attack. Without it a code is a bearer token
 * for "confirm some participation", and forwarding one to a friend with a
 * different number would confirm the wrong pair.
 *
 * Stored as a keyed hash because the value travels through Telegram, which is a
 * third party, and because a database dump must not yield replayable codes.
 */

import { DB_TIMEOUT_MS, LINK_CODE_BYTES, LINK_CODE_TTL_MS } from './config.js';
import { keyedHash, randomBytes, toBase64Url } from './crypto.js';
import { checked, getDb } from './db.js';
import { hashTelegramChatId } from './phone.js';

function hashLinkCode(code: string): Promise<string> {
  return keyedHash('BRIDGE_V2_CODE_HMAC_KEY', 'telegram-link-v1', code);
}

/**
 * Issues a code for one participant and one campaign.
 *
 * 16 bytes of CSPRNG output, base64url, so it is 22 characters and survives a
 * Telegram start parameter without escaping. The plaintext is returned once, to
 * be put in the link; only the hash is persisted.
 */
export async function issueLinkCode(participantId: string, giveawayId: bigint): Promise<string> {
  const code = toBase64Url(randomBytes(LINK_CODE_BYTES));
  const db = getDb();

  checked(
    'linkcode.insert',
    await db.from('bridge_v2_link_codes').insert({
      code_hash: await hashLinkCode(code),
      participant_id: participantId,
      giveaway_id: giveawayId.toString(),
      expires_at: new Date(Date.now() + LINK_CODE_TTL_MS).toISOString(),
    }).abortSignal(AbortSignal.timeout(DB_TIMEOUT_MS)),
  );

  return code;
}

export interface ConsumedLink {
  readonly linkId: string;
  readonly participantId: string;
  readonly giveawayId: bigint;
}

interface LinkRow {
  link_id: string;
  participant_id: string;
  giveaway_id: string;
}

function toLink(row: LinkRow): ConsumedLink {
  return {
    linkId: row.link_id,
    participantId: row.participant_id,
    giveawayId: BigInt(row.giveaway_id),
  };
}

/**
 * Binds a started link to the chat that opened it.
 *
 * The contact message that arrives next carries no code, so without this the bot
 * would have a verified number and nothing to attach it to. Writing the chat id
 * on the code row is what carries the campaign and participant across the two
 * messages.
 *
 * Not consumed here: the code is spent when the contact actually arrives, so a
 * participant who opens the link and never shares a number has not burned it.
 *
 * R4: what is written on the row is the HMAC of the chat id, never the id. The
 * bot has no need to read one back, only to recognise the same chat twice, and a
 * keyed hash does that without leaving a table that names the Telegram account
 * of every participant beside the campaign they opened.
 */
export async function claimLinkForChat(code: string, chatId: number): Promise<ConsumedLink | null> {
  const db = getDb();
  const rows = checked(
    'linkcode.claim_for_chat',
    await db.rpc('bridge_v2_claim_link_for_chat', {
      p_code_hash: await hashLinkCode(code),
      p_chat_hmac: await hashTelegramChatId(chatId),
    }).abortSignal(AbortSignal.timeout(DB_TIMEOUT_MS)),
  ) as LinkRow[] | null;

  const row = Array.isArray(rows) ? rows[0] : undefined;
  return row === undefined ? null : toLink(row);
}

/**
 * Consumes the live link for a chat, once.
 *
 * Single use is enforced by the UPDATE in the database rather than by a prior
 * read, so two deliveries of the same contact race on one statement and exactly
 * one wins. Telegram retries a delivery it did not see acknowledged, so a
 * duplicate here is expected traffic rather than an attack.
 */
export async function consumeLinkForChat(chatId: number): Promise<ConsumedLink | null> {
  const db = getDb();
  const rows = checked(
    'linkcode.consume_for_chat',
    await db
      .rpc('bridge_v2_consume_link_for_chat', { p_chat_hmac: await hashTelegramChatId(chatId) })
      .abortSignal(AbortSignal.timeout(DB_TIMEOUT_MS)),
  ) as LinkRow[] | null;

  const row = Array.isArray(rows) ? rows[0] : undefined;
  return row === undefined ? null : toLink(row);
}
